### PR TITLE
fixed gds footer bug

### PR DESCRIPTION
**Pull request by marksantoso**

### CODE REVIEW

**Comment by marksantoso** [comment]
@dominikwilkowski  Used an array for external links, please review

**Comment by dominikwilkowski** [comment]
I don't get it @marksantoso ... Let's chat about this :)

**Comment by marksantoso** [comment]
@dominikwilkowski Updated to use an object

**Comment by dominikwilkowski** [comment]
Wanna rerun `docs` so you don't delete all the files @marksantoso ?

**Pull request merged**
